apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: severityremapers.prometheus-alerting-middleware.io
spec:
  group: prometheus-alerting-middleware.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: "Ready"
          type: string
          description: "The readiness of the resource."
          jsonPath: ".status.conditions[?(@.type=='Ready')].status"

      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                map:
                  type: array
                  items:
                    type: object
                    properties:
                      alertName:
                        type: string
                      destinationSeverity:
                        type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
  scope: Cluster
  names:
    plural: severityremapers
    singular: severityremaper
    kind: SeverityRemaper
    listKind: SeverityRemapersList
    shortNames:
      - sr
