version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .docker/local.Dockerfile
    stop_signal: INT
    user: 1000:1000
    working_dir: /app
    tty: true
    volumes:
      - ./:/app:rw
#      - ~/.cache/yarn:/.cache/yarn:rw
#    env_file:
#      - .env
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: .docker/image.Dockerfile
    stop_signal: INT
    user: 1000:1000
    working_dir: /app
    tty: true