apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-app
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: api
      protocol: TCP
