{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
{{/*  - apiGroups: ["prometheus-alerting-middleware.io"]*/}}
{{/*    resources: ["severityremaper"]*/}}
{{/*    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]*/}}

  - apiGroups: ["prometheus-alerting-middleware.io"]
    resources: ["*"]
    verbs: ["*"]


{{/*  - apiGroups:*/}}
{{/*      - logging.banzaicloud.io*/}}
{{/*    resources:*/}}
{{/*      - flows*/}}
{{/*      - outputs*/}}
{{/*    verbs:*/}}
{{/*      - create*/}}
{{/*      - delete*/}}
{{/*      - deletecollection*/}}
{{/*      - get*/}}
{{/*      - list*/}}
{{/*      - patch*/}}
{{/*      - update*/}}
{{/*      - watch*/}}
{{- end }}